'use strict'

const getNextJobFromQueue = require('./lib/steps/get-next-job-from-queue')
const getFileData = require('./lib/steps/get-file-data')
const saveToNotifications = require('./lib/steps/save-to-notifications')
const prepareData = require('./lib/steps/prepare-data')
const prepareDocument = require('./lib/steps/prepare-document')
const lookupDsf = require('./lib/steps/lookup-dsf')
const lookup360 = require('./lib/steps/lookup-360')
const checkSecretAddress = require('./lib/steps/check-secret-address')
const setupDistribution = require('./lib/steps/setup-distribution')
const setupTemplates = require('./lib/steps/setup-templates')
const generateDocuments = require('./lib/steps/generate-documents')
const saveToDone = require('./lib/steps/save-to-done')
const saveToArchive = require('./lib/steps/save-to-arhive')
const saveToCallback = require('./lib/steps/save-to-callback')
const saveToDistribution = require('./lib/steps/save-to-distribution')
const saveToErrors = require('./lib/steps/save-to-errors')
const cleanupDocuments = require('./lib/steps/cleanup-documents')
const removeFromQueue = require('./lib/steps/remove-from-queue')
const logger = require('./lib/logger')

logger('info', ['index', 'start'])

getNextJobFromQueue()
  .then(getFileData)
  .then(saveToNotifications)
  .then(prepareData)
  .then(prepareDocument)
  .then(lookupDsf)
  .then(setupDistribution)
  .then(lookup360)
  .then(checkSecretAddress)
  .then(setupTemplates)
  .then(generateDocuments)
  .then(saveToDone)
  .then(saveToArchive)
  .then(saveToCallback)
  .then(saveToDistribution)
  .then(saveToErrors)
  .then(cleanupDocuments)
  .then(removeFromQueue)
  .then((data) => {
    logger('info', ['index', data._id, 'finished'])
    process.exit(0)
  })
  .catch((error) => {
    logger('error', ['index', 'error', JSON.stringify(error)])
    process.exit(1)
  })
