'use strict'

const getNextJobFromQueue = require('./lib/steps/get-next-job-from-queue')
const getFileData = require('./lib/steps/get-file-data')
const saveToNotifications = require('./lib/steps/save-to-notifications')
const prepareData = require('./lib/steps/prepare-data')
const prepareDocument = require('./lib/steps/prepare-document')
const lookupDsf = require('./lib/steps/lookup-dsf')
const lookup360 = require('./lib/steps/lookup-360')
const checkSecretAddress = require('./lib/steps/check-secret-address')
const gotAddressForDistribution = require('./lib/steps/got-address-for-distribution')
const setupDistribution = require('./lib/steps/setup-distribution')
const setupDocuments = require('./lib/steps/setup-documents')
const setupArchive = require('./lib/steps/setup-archive')
const saveToDone = require('./lib/steps/save-to-done')
const saveToArchive = require('./lib/steps/save-to-archive')
const saveToDistribution = require('./lib/steps/save-to-distribution')
const saveToErrors = require('./lib/steps/save-to-errors')
const removeFromQueue = require('./lib/steps/remove-from-queue')
const logger = require('./lib/logger')

logger('info', ['index', 'start'])

getNextJobFromQueue()
  .then(getFileData)
  .then(saveToNotifications)
  .then(prepareData)
  .then(prepareDocument)
  .then(lookupDsf)
  .then(setupDistribution)
  .then(lookup360)
  .then(checkSecretAddress)
  .then(gotAddressForDistribution)
  .then(setupDocuments)
  .then(setupArchive)
  .then(saveToDone)
  .then(saveToArchive)
  .then(saveToDistribution)
  .then(saveToErrors)
  .then(removeFromQueue)
  .then((data) => {
    logger('info', ['index', data._id, 'finished'])
    process.exit(0)
  })
  .catch((error) => {
    logger('error', ['index', 'error', JSON.stringify(error)])
    process.exit(1)
  })
