const prepareData = require('../steps/prepare-data')
const prepareDocument = require('../steps/laerekontrakt-prepare-document')
const lookupDsf = require('../steps/lookup-dsf')
const lookup360 = require('../steps/lookup-360')
const filterSecretAddress = require('../steps/filter-secret-address')
const checkSecretAddress = require('../steps/check-secret-address')
const gotAddressForDistribution = require('../steps/got-address-for-distribution')
const setupDistribution = require('../steps/setup-distribution')
const setupDocuments = require('../steps/laerekontrakt-setup-documents')
const setupArchive = require('../steps/setup-archive')
const saveToDone = require('../steps/save-to-done')
const saveToArchive = require('../steps/save-to-archive')
const saveToDistribution = require('../steps/save-to-distribution')
const saveToErrors = require('../steps/save-to-errors')
const removeFromQueue = require('../steps/remove-from-queue')
const { logger } = require('@vtfk/logger')

module.exports = data => {
  return new Promise((resolve, reject) => {
    logger('info', ['flows', 'laerekontrakt', data.studentUserName])
    prepareData(data)
      .then(lookupDsf)
      .then(filterSecretAddress)
      .then(prepareDocument)
      .then(setupDistribution)
      .then(lookup360)
      .then(checkSecretAddress)
      .then(gotAddressForDistribution)
      .then(setupDocuments)
      .then(setupArchive)
      .then(saveToDone)
      .then(saveToArchive)
      .then(saveToDistribution)
      .then(saveToErrors)
      .then(removeFromQueue)
      .then(data => {
        return resolve(data)
      })
      .catch(error => {
        logger('error', ['flows', 'laerekontrakt', error])
        return reject(error)
      })
  })
}
